name: qfar
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - scipy
  - qrcode
  - natsort
  - tqdm
  - pip
  - pip:
    - opencv-contrib-python